---
- name: Install Jenkins
  hosts: all
  remote_user: ec2-user

  tasks:
    - name: Install Java 17 (Amazon Corretto)
      yum:
        name: java-17-amazon-corretto.x86_64
        state: latest
      become: true

    - name: Add Jenkins Repository
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: true

    - name: Import Jenkins GPG Key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
      become: true

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      become: true

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
      become: true
      tags: start-jenkins

    - name: Stop Jenkins
      service:
        name: jenkins
        state: stopped
      become: true
      tags: [never, stop-jenkins]

